apiVersion: v2
name: microservice
description: Generic microservice chart for DevSecOps apps
type: application
version: 1.0.0
appVersion: "1.0.0"
dependencies:
  - name: common
    version: "*"
    repository: "file://../common"
