---
- name: Build and push Jenkins agent with Ansible
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: Load configuration from secrets file
      include_vars:
        file: "{{ playbook_dir }}/../../secrets.local.yaml"
        name: secrets

    - name: Set variables
      set_fact:
        docker_registry: "{{ DOCKERHUB_REGISTRY | default(secrets.jenkins.dockerhub_username, true) }}"
        docker_username: "{{ secrets.jenkins.dockerhub_username }}"
        docker_password: "{{ secrets.jenkins.dockerhub_password }}"
        image_name: "jenkins-agent-ansible"
        image_tag: "latest"

    - name: Log in to DockerHub
      community.docker.docker_login:
        username: "{{ docker_username }}"
        password: "{{ docker_password }}"
        registry_url: "https://index.docker.io/v1/"
      no_log: true

    - name: Build Jenkins agent image
      community.docker.docker_image:
        name: "{{ docker_registry }}/{{ image_name }}"
        tag: "{{ image_tag }}"
        build:
          path: "{{ playbook_dir }}/../../docker/jenkins-agent-ansible"
          pull: true
        source: build
        state: present
      register: build_result

    - name: Push image to DockerHub
      community.docker.docker_image:
        name: "{{ docker_registry }}/{{ image_name }}"
        tag: "{{ image_tag }}"
        push: true
        source: local
      when: build_result is succeeded

    - name: Display build summary
      debug:
        msg:
          - "Jenkins agent image built and pushed successfully"
          - "Image: {{ docker_registry }}/{{ image_name }}:{{ image_tag }}"
