---
- name: Verify Kubernetes Cluster Nodes are Ready
  hosts: localhost
  gather_facts: no

  tasks:
    - name: Wait for all nodes to be ready
      kubernetes.core.k8s_info:
        kind: Node
      register: cluster_nodes
      until: >
        cluster_nodes.resources |
        selectattr('status.conditions', 'defined') |
        map(attribute='status.conditions') | flatten |
        selectattr('type', 'equalto', 'Ready') |
        selectattr('status', 'equalto', 'True') | list | length == cluster_nodes.resources | length
      retries: 36
      delay: 5

    - name: Display nodes status
      debug:
        msg: "✓ All {{ cluster_nodes.resources | length }} nodes are Ready"
