---
- name: Store application secrets in Vault
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    vault_url: "http://localhost:8200"

  tasks:
    - name: Load configuration from secrets file
      include_vars:
        file: "{{ playbook_dir }}/../../secrets.local.yaml"
        name: secrets

    - name: Set variables from secrets
      set_fact:
        dockerhub_username: "{{ secrets.jenkins.dockerhub_username }}"
        dockerhub_password: "{{ secrets.jenkins.dockerhub_password }}"
        github_token: "{{ secrets.jenkins.github_token | default('') }}"
        git_repository: "{{ secrets.jenkins.git_repository }}"
        sonarcloud_token: "{{ secrets.jenkins.sonarcloud_token }}"
        lock_log: "{{ secrets.jenkins.lock_log | default(true) }}"

    - name: Store DockerHub credentials in Vault
      uri:
        method: PUT
        url: "{{ vault_url }}/v1/secret/data/dockerhub"
        body:
          data:
            username: "{{ dockerhub_username }}"
            password: "{{ dockerhub_password }}"
        body_format: json
        headers:
          X-Vault-Token: "{{ vault_token }}"
          X-Vault-Request: "true"
        validate_certs: false
      register: vault_dockerhub_result
      retries: 3
      delay: 2
      no_log: "{{ lock_log }}"

    - name: Store GitHub credentials in Vault
      uri:
        method: PUT
        url: "{{ vault_url }}/v1/secret/data/github"
        body:
          data:
            token: "{{ github_token }}"
            repository: "{{ git_repository }}"
        body_format: json
        headers:
          X-Vault-Token: "{{ vault_token }}"
          X-Vault-Request: "true"
        validate_certs: false
      register: vault_github_result
      retries: 3
      delay: 2
      no_log: "{{ lock_log }}"
      when: github_token != ""

    - name: Store SonarCloud credentials in Vault
      uri:
        method: PUT
        url: "{{ vault_url }}/v1/secret/data/sonarcloud"
        body:
          data:
            token: "{{ sonarcloud_token }}"
        body_format: json
        headers:
          X-Vault-Token: "{{ vault_token }}"
          X-Vault-Request: "true"
        validate_certs: false
      register: vault_sonarcloud_result
      retries: 3
      delay: 2
      no_log: "{{ lock_log }}"

    - name: Store complete configuration in Vault
      uri:
        method: PUT
        url: "{{ vault_url }}/v1/secret/data/config/complete"
        body:
          data:
            data: "{{ secrets | to_json }}"
        body_format: json
        headers:
          X-Vault-Token: "{{ vault_token }}"
          X-Vault-Request: "true"
        validate_certs: false
      register: vault_config_result
      retries: 3
      delay: 2
      no_log: "{{ lock_log }}"

    - name: Display Vault secrets storage summary
      debug:
        msg:
          - "Application secrets stored in Vault successfully"
          - "Vault URL: {{ vault_url }}"
          - "Secrets stored: dockerhub, sonarcloud{% if github_token != '' %}, github{% endif %}, config/complete"
          - "Jenkins pipelines can now access these secrets using the Vault token"
          - "Complete configuration available at secret/config/complete for loadConfig()"
