{{- define "common.externalsecret" -}}
{{- if .Values.externalSecret.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.externalSecret.name }}
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecret.refreshInterval | default "1h" }}
  secretStoreRef:
    name: {{ .Values.externalSecret.secretStore | default "vault-backend" }}
    kind: {{ .Values.externalSecret.secretStoreKind | default "SecretStore" }}
  target:
    name: {{ .Values.externalSecret.name }}-secret
    creationPolicy: Owner
  data:
  {{- range .Values.externalSecret.data }}
  - secretKey: {{ .secretKey }}
    remoteRef:
      key: {{ .remoteKey }}
      property: {{ .property }}
  {{- end }}
{{- end }}
{{- end -}}
