---
- name: Configure MongoDB credentials in Vault
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    # Default to localhost for local execution, can be overridden with -e for cluster execution
    vault_url: "{{ vault_server_url | default('http://localhost:8200') }}"
    vault_token: "{{ vault_token | default('dummy-token') }}"

  tasks:
    - name: Load secrets configuration
      include_vars:
        file: "{{ playbook_dir }}/../../secrets.local.yaml"
        name: secrets

    - name: Validate required parameters
      assert:
        that:
          - target_env is defined
          - vault_token is defined
        fail_msg: "Missing required parameters: target_env, vault_token"

    - name: Print target environment secrets
      debug:
        var: secrets.mongodb[target_env]

    - name: Set MongoDB variables
      set_fact:
        mongodb_password: "{{ secrets.mongodb[target_env].password }}"
        mongodb_username: "{{ secrets.mongodb[target_env].username }}"
        mongodb_database: "{{ secrets.mongodb[target_env].database }}"

    - name: Write MongoDB credentials to Vault
      uri:
        method: PUT
        url: "{{ vault_url }}/v1/secret-{{ target_env }}/data/mongodb"
        body:
          data:
            database: "{{ mongodb_database }}"
            username: "{{ mongodb_username }}"
            password: "{{ mongodb_password }}"
        body_format: json
        headers:
          X-Vault-Token: "{{ vault_token }}"
          X-Vault-Request: "true"
        status_code: 200
        validate_certs: false
      retries: 3
      delay: 2
      no_log: false

    - name: Success message
      debug:
        msg:
          - " MongoDB credentials stored in Vault"
          - " Path: secret-{{ target_env }}/data/mongodb"
